version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3
    steps:
      - checkout

      # Restore any previously-cached ./node_modules/ directories.
      # To force clear all cached assets, increment the "v" version in both lines below.
      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "package.json" }}
          - v6-dependencies- # Fallback to using the latest cache if no exact match is found

      - run:
          name: Install npm dependencies
          command: |
            npm install -g npm@latest && npm version && npm install
      
      - run:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              env="demo"
              extra_args="--mode default"
            else
              env="dev"
              extra_args="--mode ${CIRCLE_BRANCH} --create"
            fi

            npm run link -- "${env}"
            
            ./node_modules/.bin/moovsdk deploy moovweb react-storefront-boilerplate-dev \
              --user-email=${MOOV_EMAIL} \
              --user-password=${MOOV_PASSWORD} \
              --ignore-live \
              --deploy-id $(git rev-parse HEAD) \
              --notes "$(git rev-parse --abbrev-ref HEAD) - $(git log -1 --pretty=%B)" \
              ${extra_args}

      - save_cache:
          key: v6-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
